# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1

      - name: Install Snapcraft with LXD
        uses: samuelmeuli/action-snapcraft@v2
        with:
          use_lxd: ${{ matrix.os == 'ubuntu-18.04' }}
      - name: Build snap
        run: sg lxd -c 'snapcraft --use-lxd'
