#!/bin/sh
set -x

if [ "$(snapctl get daemon)" = "" ]
then
  if grep -q -e snap_core= -e snapd_recovery_mode= /proc/cmdline
  then snapctl set daemon=true
  else snapctl set daemon=false
  fi
fi

ls -s /usr/local/lib/etlegacy $SNAP_DATA/etlegacy
