#!/bin/sh
set -x

if [ "$(snapctl get daemon)" = "" ]
then
  if grep -q -e snap_core= -e snapd_recovery_mode= /proc/cmdline
  then snapctl set daemon=true
  else snapctl set daemon=false
  fi
fi

exec ${HOME}/snap/etlegacy/current/bin/setup.sh

cp -R $SNAP/usr/local/lib/etlegacy/legacy $SNAP_USER_DATA/.etlegacy
cp -R $SNAP/usr/local/lib/etlegacy/etmain $SNAP_USER_DATA/.etlegacy
